# Generated by Django 4.0.4 on 2022-06-08 14:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_main', models.ImageField(upload_to='')),
                ('title_main', models.CharField(max_length=150)),
                ('description_main', models.TextField(max_length=1000)),
                ('image_one', models.ImageField(blank=True, upload_to='')),
                ('title_one', models.CharField(max_length=150)),
                ('description_one', models.TextField(max_length=1000)),
                ('image_two', models.ImageField(blank=True, upload_to='')),
                ('title_two', models.CharField(max_length=150)),
                ('description_two', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 3, 26, 437855, tzinfo=utc))),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('number_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('facebook_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('likedin_link', models.URLField()),
                ('instagram_link', models.URLField()),
                ('youtube_link', models.URLField()),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 3, 26, 454855, tzinfo=utc))),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 3, 26, 452855, tzinfo=utc))),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 3, 26, 440855, tzinfo=utc))),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 3, 26, 439855, tzinfo=utc))),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 3, 26, 436855, tzinfo=utc))),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogoCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('url', models.URLField(blank=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 3, 26, 441856, tzinfo=utc))),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 3, 26, 438855, tzinfo=utc))),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 3, 26, 452855, tzinfo=utc))),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='')),
                ('facebook_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('likedin_link', models.URLField()),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 3, 26, 453855, tzinfo=utc))),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.designation')),
            ],
        ),
    ]
