# Generated by Django 4.0.4 on 2022-06-08 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 6, 12, 627982, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contactcompany',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 6, 12, 641982, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='designation',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 6, 12, 639982, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feature',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 6, 12, 630982, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='featuredescription',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 6, 12, 629982, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='indexfront',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 6, 12, 626982, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='logocompany',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 6, 12, 631982, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 6, 12, 628982, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 6, 12, 640982, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 6, 12, 639982, tzinfo=utc)),
        ),
    ]
