# Generated by Django 4.0.4 on 2022-06-14 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_alter_about_created_alter_about_image_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 13, 9, 50, 415018, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='about',
            name='image_two',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contactcompany',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 13, 9, 50, 421171, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='designation',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 13, 9, 50, 420258, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feature',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 13, 9, 50, 416182, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='featuredescription',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 13, 9, 50, 415841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='indexfront',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 13, 9, 50, 413791, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='logocompany',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 13, 9, 50, 416541, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 13, 9, 50, 415489, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 13, 9, 50, 420653, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 13, 9, 50, 419844, tzinfo=utc)),
        ),
    ]
