# Generated by Django 4.0.4 on 2022-06-14 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_alter_about_created_alter_about_image_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 14, 14, 47, 944703, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contactcompany',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 14, 14, 47, 951319, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='designation',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 14, 14, 47, 950462, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feature',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 14, 14, 47, 946008, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='featuredescription',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 14, 14, 47, 945651, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='indexfront',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 14, 14, 47, 943519, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='logocompany',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 14, 14, 47, 946418, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 14, 14, 47, 945196, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 14, 14, 47, 950837, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='photo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 14, 14, 47, 950041, tzinfo=utc)),
        ),
    ]
