# Generated by Django 4.0.4 on 2022-06-08 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_contact_created_alter_newsletter_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 10, 15, 15822, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 10, 15, 14823, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 10, 15, 14823, tzinfo=utc)),
        ),
    ]
