# Generated by Django 4.0.4 on 2022-06-09 12:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_user_photo_alter_contact_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 12, 2, 41, 151099, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 12, 2, 41, 149099, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 12, 2, 41, 150099, tzinfo=utc)),
        ),
    ]
